version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: leafbro_elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=your_elastic_password
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.license.self_generated.type=trial
      - ES_JAVA_OPTS=-Xms2g -Xmx2g  # Adjust the heap size
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - backtier_network
    deploy:
      resources:
        limits:
          memory: 4g  # Adjust memory limit
        reservations:
          memory: 1g  # Ensure at least this much memory is reserved
  api:
    build:
      context: .
      dockerfile: ./services/api/Dockerfile
    # command: >
    #   uvicorn src.main:app  --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - elasticsearch
    env_file:
      - .env
    volumes:
      - ./data:/srv/data
      - ./services/api/src:/srv/src
    ports:
      - "8000:8000"
    networks:
      - backtier_network
    container_name: green_buddy_api
volumes:
  es-data:
    driver: local

networks:
  backtier_network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450